### ISSUE TITLE
trying to run the project  

### ISSUE THREAD

**Issue by pelegsheleg** [morpheuslord/GPT_Vuln-analyzer#1]
hello iam trying to run the projet but iam encountering an error regarding the path of nmap in the system 
i downloaded the software as well on the system and add the path for the nmap in the environment variables i would love for you to contact me please thanks !

**Comment by morpheuslord** [comment]
You have to install the nmap program on your system. Download from [nmap](https://nmap.org) if for windows 
if for Linux run:
```
sudo apt-get update && sudo apt-get upgrade -y
sudo apt-get install nmap
```
